// @vitest-environment node
import Database from 'better-sqlite3'
import { afterAll, expect, it, vi } from 'vitest'
vi.mock('server-only', () => ({}))
const database = new Database(':memory:')
database.exec('CREATE TABLE access_revocation (id TEXT PRIMARY KEY, user_id TEXT, media_path TEXT, created_at INTEGER, chat_done INTEGER DEFAULT 0, media_done INTEGER DEFAULT 0)')
vi.mock('@/lib/auth/database', () => ({ getDatabase: () => database }))
const mocks = vi.hoisted(() => ({ chat: vi.fn(), media: vi.fn() }))
vi.mock('@/lib/chat-realtime', () => ({ disconnectChatParticipant: mocks.chat }))
vi.mock('@/lib/mediamtx', () => ({ disconnectChannelReaders: mocks.media, disconnectAllWebRtcReaders: mocks.media }))
afterAll(() => database.close())
it('does not repeat successful video disconnections while Chat retries', async () => {
  const { dispatchAccessRevocations } = await import('./access-revocations')
  database.prepare('INSERT INTO access_revocation (id, user_id, created_at) VALUES (?, ?, ?)').run('one', 'viewer', 0)
  mocks.chat.mockRejectedValue(new Error('Chat unavailable'))
  mocks.media.mockResolvedValue(undefined)
  await dispatchAccessRevocations()
  await dispatchAccessRevocations()
  expect(mocks.media).toHaveBeenCalledTimes(1)
  expect(mocks.chat).toHaveBeenCalledTimes(2)
  expect(database.prepare('SELECT media_done FROM access_revocation').get()).toEqual({ media_done: 1 })
  mocks.chat.mockResolvedValue(undefined)
  await dispatchAccessRevocations()
  expect(database.prepare('SELECT * FROM access_revocation').all()).toEqual([])
  expect(mocks.media).toHaveBeenCalledTimes(1)
})
it('processes new media revocations while a full batch of Chat retries remains pending', async () => {
  const { dispatchAccessRevocations } = await import('./access-revocations')
  mocks.chat.mockRejectedValue(new Error('Chat unavailable'))
  mocks.media.mockClear()
  for (let index = 0; index < 21; index++) database.prepare('INSERT INTO access_revocation (id, user_id, created_at, media_done) VALUES (?, ?, ?, ?)').run(`batch-${index}`, 'viewer', index, index < 20 ? 1 : 0)
  await dispatchAccessRevocations()
  expect(mocks.media).toHaveBeenCalledTimes(1)
  expect(database.prepare('SELECT media_done FROM access_revocation WHERE id = ?').get('batch-20')).toEqual({ media_done: 1 })
})
